
import React, { useState } from 'react';
import { Product, InquiryData } from '../types';
import SectionTitle from '../components/SectionTitle';
import { Send, Mail, User, Info, Package, ShieldCheck, CheckCircle2, ChevronRight, Building, Loader2 } from 'lucide-react';

interface InquiryProps {
  product: Product;
  onAddInquiry: (inquiry: InquiryData) => Promise<void>;
}

const Inquiry: React.FC<InquiryProps> = ({ product, onAddInquiry }) => {
  const [formState, setFormState] = useState({
    name: '',
    email: '',
    company: '',
    quantity: '100'
  });
  const [submitted, setSubmitted] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    try {
      const newInquiry: InquiryData = {
        id: '', // Generated by Supabase
        productId: product.id,
        productName: product.name,
        name: formState.name,
        email: formState.email,
        company: formState.company,
        quantity: formState.quantity,
        message: 'Direct Inquiry',
        requirement: 'Standard',
        timestamp: new Date().toISOString()
      };

      await onAddInquiry(newInquiry);
      setSubmitted(true);
    } catch (err) {
      console.error(err);
      alert('Error submitting inquiry. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const inputClasses = "w-full px-5 py-4 rounded-2xl border border-slate-200 focus:ring-2 focus:ring-red-500 outline-none transition-all bg-slate-50 focus:bg-white text-slate-900 font-medium placeholder:text-slate-300 shadow-sm";
  const labelClasses = "block text-xs font-black text-slate-400 mb-3 uppercase tracking-[0.2em] ml-1";

  return (
    <div className="pt-32 pb-24 bg-slate-50 min-h-screen animate-in fade-in duration-500">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col lg:flex-row gap-16">
          
          <div className="lg:w-2/5">
            <div className="sticky top-32">
              <div className="inline-flex items-center px-4 py-1.5 bg-red-600 text-white rounded-full text-[10px] font-black uppercase tracking-widest mb-6 shadow-lg shadow-red-200">
                Inquiry Context
              </div>
              <h1 className="text-5xl font-black text-slate-900 mb-8 tracking-tighter leading-tight">Request a <span className="text-red-600">Quote</span></h1>
              
              <div className="bg-white rounded-[2.5rem] border border-slate-100 overflow-hidden shadow-2xl">
                <div className="aspect-[4/3] w-full overflow-hidden bg-slate-100">
                  <img src={product.image} alt={product.name} className="w-full h-full object-cover" />
                </div>
                <div className="p-10">
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{product.category}</span>
                    <span className="text-[10px] font-black text-red-600 uppercase tracking-widest">ID: {product.id.toString().slice(-8)}</span>
                  </div>
                  <h2 className="text-3xl font-black text-slate-900 mb-4">{product.name}</h2>
                  <p className="text-slate-500 text-sm leading-relaxed mb-8">{product.description}</p>
                  
                  <div className="space-y-4 pt-6 border-t border-slate-50">
                    <div className="flex items-center gap-4 text-xs font-bold text-slate-700">
                      <div className="w-8 h-8 rounded-full bg-red-50 flex items-center justify-center text-red-600">
                        <ShieldCheck size={18} />
                      </div>
                      Certified Protection Standard
                    </div>
                    <div className="flex items-center gap-4 text-xs font-bold text-slate-700">
                      <div className="w-8 h-8 rounded-full bg-red-50 flex items-center justify-center text-red-600">
                        <Package size={18} />
                      </div>
                      Global Bulk Distribution Available
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-8 p-8 bg-slate-900 rounded-3xl border border-slate-800 shadow-xl">
                <div className="flex gap-4">
                   <Info className="text-red-500 flex-shrink-0" />
                   <p className="text-sm font-medium text-slate-300 leading-relaxed">
                     A <span className="text-white font-bold">CareGuard sterilization specialist</span> will review your request and provide a tiered volume pricing proposal within <span className="text-red-400 font-bold">4 business hours</span>.
                   </p>
                </div>
              </div>
            </div>
          </div>

          <div className="lg:w-3/5">
            <div className="bg-white p-12 lg:p-16 rounded-[3.5rem] shadow-2xl border border-slate-100 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-red-50/50 rounded-full -mr-32 -mt-32 blur-3xl"></div>
              
              {submitted ? (
                <div className="py-24 flex flex-col items-center justify-center text-center animate-in zoom-in duration-500 relative z-10">
                  <div className="w-28 h-28 bg-red-100 text-red-600 rounded-full flex items-center justify-center mb-10 shadow-inner">
                    <CheckCircle2 size={56} />
                  </div>
                  <h3 className="text-4xl font-black text-slate-900 mb-4 tracking-tighter">INQUIRY DISPATCHED</h3>
                  <p className="text-slate-400 font-bold uppercase tracking-widest text-xs mb-10">Sync Complete with Secure Ledger</p>
                  <p className="text-xl text-slate-600 max-w-sm mb-12 font-medium">
                    Your request for <strong>{product.name}</strong> has been prioritized. Our procurement team will contact you shortly.
                  </p>
                  <button 
                    onClick={() => window.location.hash = '/products'} 
                    className="bg-slate-900 text-white font-black px-12 py-5 rounded-2xl uppercase tracking-widest text-sm hover:bg-red-600 transition-all shadow-xl"
                  >
                    Return to Catalog
                  </button>
                </div>
              ) : (
                <div className="relative z-10">
                  <div className="mb-12">
                    <h3 className="text-3xl font-black text-slate-900 mb-2 tracking-tight">Direct Procurement Form</h3>
                    <p className="text-slate-500 font-medium">Please provide your professional contact details for a rapid response.</p>
                  </div>

                  <form onSubmit={handleSubmit} className="space-y-10">
                    <div className="space-y-8">
                      <div>
                        <label className={labelClasses}>
                          <User size={12} className="inline mr-1 mb-0.5 text-red-600" /> Full Identity
                        </label>
                        <input 
                          required
                          disabled={isSubmitting}
                          className={inputClasses}
                          placeholder="Mohammad Ali"
                          value={formState.name}
                          onChange={e => setFormState({...formState, name: e.target.value})}
                        />
                      </div>
                      
                      <div>
                        <label className={labelClasses}>
                          <Mail size={12} className="inline mr-1 mb-0.5 text-red-600" /> Corporate Communication
                        </label>
                        <input 
                          required
                          disabled={isSubmitting}
                          type="email"
                          className={inputClasses}
                          placeholder="saiyedmohammadali56@gmail.com"
                          value={formState.email}
                          onChange={e => setFormState({...formState, email: e.target.value})}
                        />
                      </div>

                      <div>
                        <label className={labelClasses}>
                          <Building size={12} className="inline mr-1 mb-0.5 text-red-600" /> Company / Institution
                        </label>
                        <input 
                          required
                          disabled={isSubmitting}
                          className={inputClasses}
                          placeholder="St. Mary's Hospital"
                          value={formState.company}
                          onChange={e => setFormState({...formState, company: e.target.value})}
                        />
                      </div>

                      <div className="pt-4">
                        <label className={labelClasses}>Target Distribution Quantity</label>
                        <div className="relative">
                          <input 
                            required
                            disabled={isSubmitting}
                            type="number"
                            className={inputClasses}
                            placeholder="Units required"
                            value={formState.quantity}
                            onChange={e => setFormState({...formState, quantity: e.target.value})}
                          />
                          <div className="absolute right-5 top-1/2 -translate-y-1/2 text-slate-400 text-xs font-black uppercase tracking-widest">
                            Units
                          </div>
                        </div>
                      </div>
                    </div>

                    <button 
                      type="submit"
                      disabled={isSubmitting}
                      className="w-full bg-red-600 text-white font-black py-7 rounded-[2rem] shadow-2xl hover:bg-red-700 disabled:bg-slate-300 transition-all flex items-center justify-center gap-4 text-2xl tracking-tighter group"
                    >
                      {isSubmitting ? <Loader2 size={28} className="animate-spin" /> : <Send size={28} className="group-hover:-translate-y-1 group-hover:translate-x-1 transition-transform" />}
                      {isSubmitting ? 'TRANSMITTING...' : 'SEND QUOTE REQUEST'}
                    </button>
                    
                    <div className="flex items-center gap-4 p-6 bg-slate-50 rounded-2xl border border-slate-100">
                      <div className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center text-slate-400">
                        <ShieldCheck size={20} />
                      </div>
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest leading-relaxed">
                        Secure Backend Powered by Supabase | AES-256 Encryption
                      </p>
                    </div>
                  </form>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Inquiry;
